import React from 'react';
import PropTypes from 'prop-types';

const TermsAndConditions = props => {
  return (
    <div className='container text-deep'>
      <p className='large'>
        Blood Source Terms and Conditions, Data and Cookie Policies
      </p>
      <p>
        Legal Terms <br />
        <br />
        GENERAL: - <br />
        <br />• This electronic record is generated by a computer system and
        does not require any physical or digital signature.
        <br />• By accessing the Website or Application, whether through a
        mobile device, mobile application or computer, the User agrees to be
        bound by these Terms of Use ("Terms") and the Privacy Policy ('Policy'),
        whether or not the User creates an account to avail of the Service. If
        the User wishes to avail of the Service, the User does hereby
        unequivocally accept and agree to the contents of these Terms and the
        Policy.
        <br />
        <br />
        ACCEPTANCE OF TERMS: - <br />
        <br />
        The User is aware and agrees that the Company reserves the sole and
        exclusive right to amend or modify these Terms without any prior
        permission or intimation to the User, and the User expressly agrees that
        any such amendments or modifications shall come into effect immediately.
        The User has a duty to periodically check the terms and stay updated on
        its requirements. If the User continues to use the Application following
        such a change, the User will be deemed to have consented to any and all
        amendments / modifications made to the Terms. In so far as the User
        complies with these Terms, he/she is granted a personal, non-exclusive,
        non-transferable, revocable, limited privilege to access and use the
        Application. <br />
        <br />
        CREATION OF AN ACCOUNT AND REGISTRATION: - <br />
        <br />• In order to use Service, the User must first provide certain
        details to the Company through the Application, including but not
        limited to the User's name, age, sex, blood type, blood requirement,
        eligibility, mobile phone number, email address, photographs, user name,
        password, geographical location, etc., to create an account that can
        subsequently be used to avail of the Service. The User agrees that all
        information provided to the Company shall be accurate to the best of the
        User's knowledge, belief and information, and shall be updated whenever
        appropriate, in a timely manner. The User hereby authorizes the Company
        to access and use any and all such information provided, as governed by
        these Terms and the Policy. <br />
        <br />
        TERM AND TERMINATION: - <br />
        <br />
        These Terms will remain in full force and effect while the User avails
        of the Service and/or is in possession of an active account. The User is
        aware that the Company may terminate or suspend the User's account at
        any time, without cause or notice, if the Company believes that the User
        has breached the Terms or Policy, or for any other reason, in its sole
        discretion. The User is further aware and expressly agrees that even
        after the User's account is terminated for any reason, these Terms and
        the Policy shall survive such termination, and continue to operate in
        full force and effect, except for any terms that by their nature expire
        or are fully satisfied. <br />
        <br />
        NON-COMMERCIAL USE BY USERS: - <br />
        <br />
        The Service is only for the personal use of the User. The User may not
        use the Service or any content contained in the Service (including, but
        not limited to, content of other users or establishments, designs, text,
        graphics, images, video, information, logos, software, audio files and
        computer code) in connection with any commercial endeavors, including
        but not limited to advertising or soliciting any User to buy or sell any
        products or services not offered by the Company or through the
        Application. The User may not use any information obtained from the
        Service to contact, advertise to, solicit, or sell any product/service
        to any other User, either within the Application or otherwise.
        Organizations, companies, and/or businesses may not use the Application
        or the Service for any purpose. The Company may investigate and take any
        available legal action in response to illegal and/or unauthorized uses
        of the Service, including the collection of usernames and/or email
        addresses of other users by electronic or other means, for the purpose
        of sending unsolicited email and unauthorized framing of or linking to
        the Application or Service. <br />
        <br />
        ROLE AND RESPONSIBILITY OF THE COMPANY: - <br />
        <br />• Upon registration as a Member after filling the form and
        providing details, the Application will provide You with facility to
        avail the Services, where You can raise a request for blood of a certain
        type, browse existing requests for blood of a certain type and see
        suggestions based on Your blood group type or preferences for a
        potential match with other Users or Members. <br />• Raising a request
        for blood entails filling up a form wherein preferences are required to
        be mentioned by You, including but not limited to the blood type
        required, along with geographical location details. The request will
        then be shared by the Application with other Members. <br />• We will
        endeavor to provide Member profile(s) as per your set preferences
        subject to availability of profile in the database of the Application.{' '}
        <br />• Suggestions made by Application are based on the data provided
        by the Members in their blood group type preferences, and other
        technological factors. Each Member agrees to exercise due care and
        caution while proceeding with meeting/contacting with a matched Member
        profile. <br />• The availability of Member profiles depends on the
        number of registered Members, and We undertake no obligation to provide
        You with any definite number of profiles. <br />• We will provide You
        all assistance related to our Application and take appropriate measures
        to resolve any complaints which you may have in relation to our
        Application. <br />• It shall be the responsibility of the Company to
        display the Member profiles in a form decided by Us, and to take
        appropriate measures for any Member's account if We receive any
        complaint from any of our Members against another Member. <br />• In the
        event that it is found that a false complaint is filed by any Member,
        then it is the victim Member's responsibility to take appropriate action
        if any at their own expense, and the Company is not liable for the same.{' '}
        <br />• We may provide You with reasonable assistance, to be determined
        at the discretion of the Company, in providing any information pursuant
        to an order of a competent enforcement or judicial authority, provided
        that any expenses in doing so is to be borne by the Member who has taken
        any action. The same is notwithstanding the result of any such claim or
        action taken before any such authority. <br />• The profiles shared with
        Members are from the data available with the Application. We do not make
        any representations as to the accuracy and authenticity or otherwise in
        relation to any such data either provided at the time of registration or
        maintained subsequently. Our one-time password method only provide an
        assurance that the mobile number provided at the time of registration
        was in active state. <br />
        <br />
        Role and Responsibility of Member/ User: - <br />
        <br />• Members agree that a basic prerequisite for use of the Website
        is easy access to the internet and internet browsing facilities
        supported by the website, as well as a working phone number by which the
        Member is accessible. All expenses in relation to the same are to be
        borne entirely by the Members, and Members further agree that the
        Company shall not be liable for any
        shortcomings/deficiencies/interruptions/mistakes/down time of any nature
        in the services provided for by the internet/telecom service
        provider(s). <br />• Members agree to exercise due care and caution
        while shortlisting other Members and satisfy themselves before making a
        choice of the match through adequate efforts, initiatives and due
        diligence. We are not liable for the consequences of any
        misrepresentations made by any Members to You. However, if it is
        reported or found by us that any Member's profile is misleading or
        inaccurate or any Member is not in conformity with these Terms and
        Privacy Policy, then We reserve the right to suspend, terminate or block
        such a Member at the discretion of the Company <br />• Members agree to
        verify the credentials of other Members such as blood group type, blood
        donation/requirement eligibility, medical status, contact details,
        character, etc. <br />• Members shall disclose their proper health
        records and blood group type specific information (if applicable) in the
        form and keep such information up to date at all times. Such health
        information may include but is not limited to any pre-existing illness.
        Non-disclosure of such information or inaccurate disclosure of such
        information at all times shall be treated as violation of the Terms and
        Policy. <br />
        <br />
        Members are expected to refrain from: <br />
        <br />• Entering into financial transactions with shortlisted prospects.{' '}
        <br />• Dealing with shortlisted prospects in any manner before carrying
        out due verifications of the prospect. <br />• Entering into any
        deal/contract with prospect outside the Application. <br />• Sharing of
        confidential and personal data with each other. <br />• Members are
        expected to be cautious of Members who call from multiple numbers, only
        interact over phone, doesn't come forward for face to face meetings
        (physically or through video calls) upon request and don't involve
        family and friends in blood request matching. <br />• Members cannot use
        the profile shared to them for the benefit of any third person(s) or for
        gaining any commercial benefits and any contravention of the same shall
        amount to a violation of these Terms. <br />• Membership for the
        purposes of blood request match over our Application is restricted
        strictly to the registered individual Members only. Member's data cannot
        be used for any commercial purpose or for competitive business or for
        any other purpose than specified purpose of match between blood donor
        and blood seeker or such other purpose as may be notified by Us from
        time to time. <br />• You shall not assign or transfer Your Membership
        to any other person or entity. <br />• We and our partners may contact
        you over phone / e-mail / SMS and in such technological modes as are
        prevailing in the market, and by submitting the form, you waive any
        right to treat such communication as unsolicited commercial
        communication notwithstanding the fact that your number is registered
        under the National Do Not Call Registry or any other registry
        established for similar purposes. <br />• In the event of any
        contravention of these Terms or Policy by any Member, the Company
        reserves our right to initiate appropriate legal action against the
        concerned Member. <br />
        <br />
        ACCOUNT SECURITY: - <br />
        <br />
        The User is responsible for maintaining the confidentiality of his/her
        username and password, assigned to the User during the registration
        process, and the User is solely responsible for all activities that
        occur under the User's username and password. The User agrees to
        immediately notify the Company of any disclosure or unauthorized use of
        the User's username or password, or any other breach of security with
        respect to the User's account, and also ensure that he/she logs out from
        his/her account at the end of each session. <br />
        <br />
        INTERACTIONS WITH OTHER USERS: - <br />
        <br />• The User agrees and acknowledges that the User is solely
        responsible for his/her interactions with other users. The User
        understands that the Company does not conduct any background checks,
        medical checks or screenings on any of its Users. The User is further
        aware that the Company also does not inquire into the backgrounds of any
        of its users or attempt to verify the statements of its Users. The
        Company makes no representations or warranties as to the conduct of its
        Users, or the information / material made available by them to other
        Users, and the User expressly agrees and acknowledges that the Company
        will not be liable for the same in any manner whatsoever. <br />
        <br />
        PROPRIETARY RIGHTS: - <br />
        <br />
        Two owner named Md.Badruddoza and Dipankar Bhadra <br />
        <br />
        CONTENT POSTED BY THE USER: - <br />
        <br />• The User acknowledges and agrees that he/she is solely
        responsible for the content and information that he/she posts, uploads,
        publishes, links to, transmits, records, displays or otherwise makes
        available on the Service or transmits to other users, including text
        messages, chat, photographs, whether posted on the Website or
        Application, or privately transmitted to other Users. The User may not
        Post as part of the Service, or transmit to the Company or to any other
        user (either on or off the Service), any offensive, inaccurate,
        incomplete, abusive, obscene, profane, threatening, intimidating,
        harassing, racially offensive, or illegal material, or any material that
        infringes or violates another person's rights (including intellectual
        property rights, and rights of privacy and publicity). The User
        represents and warrants that all information that the User submits upon
        creation of the account is accurate and truthful, and that the User will
        promptly update any information that subsequently becomes inaccurate,
        incomplete, misleading or false. <br />• The User understands and agrees
        that the Company may, but is not obligated to, monitor or review any
        content the User posts as part of the Service. The Company may delete
        any content, in whole or in part, that in the sole judgment of the
        Company violates these Terms or may harm the reputation of the
        Application, Website, Service or Company. <br />• The User may not post,
        upload, display or otherwise make available content that: <br />
        <br />
        1. promotes racism, bigotry, hatred or physical harm of any kind against
        any group or individual; <br />
        2. advocates harassment or intimidation of another person; <br />
        3. is intended to otherwise defraud other users of the Service; <br />
        4. involves the transmission of 'junk mail', 'chain letters', or
        unsolicited mass mailing or 'spamming' (or 'spimming', 'phishing',
        'trolling' or similar activities); <br />
        5. promotes information that is false or misleading, or promotes illegal
        activities or conduct that is defamatory, libelous or otherwise
        objectionable; <br />
        6. promotes an illegal or unauthorized copy of another person's
        copyrighted work; <br />
        7. contains video, audio photographs, or images of another person
        without his or her permission (or in the case of a minor, the minor's
        legal guardian); <br />
        8. contains restricted or password only access pages, or hidden pages or
        images (those not linked to or from another accessible page); <br />
        9. provides material that exploits people in a sexual, violent or other
        illegal manner, or solicits personal information from anyone under the
        age of 18; <br />
        10. provides instructional information about illegal activities such as
        making or buying illegal weapons or drugs, violating someone's privacy,
        or providing, disseminating or creating computer viruses; <br />
        11. contains viruses, time bombs, trojan horses, cancelbots, worms or
        other harmful, or disruptive codes, components or devices; <br />
        12. impersonates, or otherwise misrepresents affiliation, connection or
        association with, any person or entity; <br />
        13. provides information or data the User do not have a right to make
        available under law or under contractual or fiduciary relationships
        (including, but not limited to inside information, proprietary and
        confidential information); <br />
        14. disrupts the normal flow of dialogue, causes a screen to 'scroll'
        faster than other users are able to type, or otherwise negatively
        affects other users' ability to engage in real time exchanges; <br />
        15. solicits passwords or personal identifying information for
        commercial or unlawful purposes from other users or disseminates another
        person's personal information without his or her permission; and
        <br />
        16. publicizes or promotes commercial activities and/or sales without
        our prior written consent such as contests, sweepstakes, barter,
        advertising, and pyramid schemes. <br />
        <br />• The Company reserves the right, in its sole discretion, to
        investigate and take any legal action against any User who violates this
        provision, including removing the offending communication from the
        Service and terminating or suspending the account of such User. <br />•
        The User's use of the Service, including all content posted by the User
        through the Service, must comply with all applicable laws and
        regulations. The User agrees and acknowledges that the Company may
        access, preserve and disclose the User's account information and content
        if required to do so by law, or if it in good faith believes that such
        access, preservation or disclosure is reasonably necessary, to: <br />
        <br />
        1. comply with any legal process; <br />
        2. enforce these Terms; <br />
        3. respond to claims that any content violates the rights of third
        parties; <br />
        4. respond to the User's requests for customer service, or allow the
        User to use the Service in the future; or <br />
        5. protect the rights, property or personal safety of the Company or any
        other person. • The User agrees that any content the User posts on the
        Service may be viewed by other users and may be viewed by any person
        visiting or participating in the Service. <br />
        <br />
        INDEMNITY: - <br />
        <br />
        Any Member's conduct, personal interaction either over the Website or
        otherwise, and any communication or transactions of any nature are
        outside the purview of the scope of Service of the Company, and each
        Member agrees to indemnify and hold Us harmless in relation to the same.
        Any and all Members also agree to hold all the
        Directors/officials/employees and persons associated with the Company,
        Application and Website harmless in relation to the same. <br />
        <br />
        PROHIBITED ACTIVITIES: - <br />
        <br />
        The Company reserves the right to investigate, suspend and/or terminate
        the User account if the User has misused the Service or behaved in a
        manner the Company regards as inappropriate or unlawful, including
        actions or communications that occur off the Service, but involve users
        of the Service or information obtained through the Service. The
        following is a non-exclusive list of actions and activities that the
        User is not permitted to engage in while availing of the Service: <br />
        <br />• impersonate any person or entity; <br />• post any content that
        is prohibited by these Terms or any applicable law currently in force;{' '}
        <br />• stalk or otherwise harass any person; <br />• express or imply
        that any statements the User makes are endorsed by the Company without
        the Company's specific prior written consent; <br />• use the Service in
        an illegal manner or to commit an illegal act; <br />• ask or use users
        to conceal the identity, source, or destination of any illegally gained
        money or products; <br />• use any robot, spider, site search/retrieval
        application, or other manual or automatic device or process to retrieve,
        index, "data mine", or in any way reproduce or circumvent the
        navigational structure or presentation of the Service or its contents;{' '}
        <br />• collect usernames and/or email addresses of users by electronic
        or other means for the purpose of sending unsolicited email or
        unauthorized framing of or linking to the Service; <br />• interfere
        with or disrupt the Service or the servers or networks connected to the
        Service; <br />• email or otherwise transmit any material that contains
        software viruses, or any other computer code, files or programs designed
        to interrupt, destroy or limit the functionality of any computer
        software or hardware or "frame" or "mirror" any part of the Service,
        without the Company's prior written authorization; <br />• use meta
        telecommunications equipment; <br />• forge headers or otherwise
        manipulate identifiers in order to disguise the origin of any
        information transmitted to or through the Service (either directly or
        indirectly through use of third-party software); <br />• tags or code or
        other devices containing any reference to the Company or the Service (or
        any trademark, trade name, service mark, logo or slogan of the Company)
        to direct any person to any other website for any purpose; <br />•
        modify, adapt, sublicense, translate, sell, reverse engineer, decipher,
        decompile or otherwise disassemble any portion of the Service any
        software used on or for the Service, or cause others to do so; <br />•
        post, use, transmit or distribute, directly or indirectly, (e.g. screen
        scrape) in any manner or media any content or information obtained from
        the Service other than solely in connection with the User use of the
        Service in accordance with these Terms. <br />
        <br />
        CUSTOMER SERVICE: - <br />
        <br />
        The Company may provide assistance and guidance through its customer
        care representatives. When communicating with the Company's customer
        care representatives, the User agrees to not be abusive, obscene,
        profane, offensive, sexist, threatening, harassing, racially offensive,
        and to not otherwise behave inappropriately. If the Company is of the
        impression that the User's behavior towards any of its customer care
        representatives or other employees is at any time threatening or
        offensive as described hereinabove, the Company reserves the right to
        immediately terminate the User's account. <br />
        <br />
        MODIFICATIONS TO SERVICE: -<br />
        <br />
        The Company reserves the right at any time to modify or discontinue,
        temporarily or permanently, the Website, Application or Service (or any
        part thereof) with or without notice. The User agrees and acknowledges
        that the Company shall not be liable to the User or to any third party
        for any modification, suspension or discontinuance of the Service. To
        protect the integrity of the Service, the Company reserves the right to
        block users from certain IP addresses from accessing the Service, at any
        time and in its sole discretion. <br />
        <br />
        DISCLAIMERS: - <br />
        <br />• The User acknowledges and agrees that neither the Company nor
        its affiliates or third-party partners are responsible for, and shall
        not be deemed to have any liability - directly or indirectly, any loss
        or damage, including personal injury or death, as a result of or alleged
        to be the result of
        <br />• any incorrect or inaccurate content posted in the Service,
        whether caused by users or any of the equipment or programming
        associated with or utilized in the Service; <br />• the timeliness,
        deletion or removal, incorrect delivery or failure to store any content,
        communications or personalization settings; <br />• the conduct, whether
        online or offline, of any user; <br />• any error, omission or defect
        in, interruption, deletion, alteration, delay in operation or
        transmission, theft or destruction of, or unauthorized access to, any
        user or user communications; <br />• any problems, failure or technical
        malfunction of any telephone network or lines, computer online systems,
        servers or providers, computer equipment, software, failure of email or
        any other online portal/facility on account of technical problems or
        traffic congestion on the Internet or at any website or combination
        thereof, including injury or damage to users or to any other person's
        computer or device related to or resulting from participating or
        downloading materials in connection with the Internet and/or in
        connection with the Service, and the User hereby expressly acknowledges
        and agrees that the Company has no responsibility or control over the
        same. <br />• The User is aware and acknowledges that to the maximum
        extent allowed by applicable laws, the Company provides the Service on
        an "as is" and "as available" basis, and grants no warranties of any
        kind, whether express, implied, statutory or otherwise with respect to
        the Service (including all content contained therein), including
        (without limitation) any implied warranties of satisfactory quality,
        merchantability, fitness for a particular purpose or non-infringement.
        The Company does not represent or warrant that the Service will be
        uninterrupted or error free, secure or that any defects or errors in the
        Service will be corrected. <br />• The Company may make third party
        opinions, advice, statements, offers, or other third-party information
        or content available through the Service. The User is aware that all
        such third-party content is the responsibility of the respective authors
        thereof, and the Company does not make any warranties or guarantees with
        respect to the same. The User is further aware that the Company does
        not: <br />
        <br />
        1. guarantee the accuracy, completeness, or usefulness of any
        third-party content provided through the Service, or
        <br />
        2. adopt, endorse or accept responsibility for the accuracy or
        reliability of any opinion, advice, or statement made by any party that
        appears in the Service. The User agrees and acknowledges that under no
        circumstances will the Company or its affiliates be responsible or
        liable for any loss or damage resulting from the user reliance on
        information or other Content posted in the Service or transmitted to or
        by any users. <br />
        <br />
        LIMITATION OF LIABILITY: - <br />
        <br />• If any type of occurrence occurred no one of the agency
        (Directors/staffs/Well-wishers) will be liable. The Parties
        (Donor/Needed) expressly agree that. <br />• Agency is not bound to help
        any of the two Parties (Donor/Needed). The Parties (Donor/Needed)
        expressly agree that. <br />
        <br />
        PRIVACY POLICY: - <br />
        <br />• This electronic record is generated by a computer system and
        does not require any physical or digital signature. <br />• By accessing
        the Website or Application, whether through a mobile device, mobile
        application or computer, the User agrees to be bound by these Terms of
        Use ("Terms") and the Privacy Policy ('Policy'), whether or not the User
        creates an account to avail of the Service. If the User wishes to avail
        of the Service, the User does hereby unequivocally accept and agree to
        the contents of these Terms and the Policy. <br />• The headings of each
        section in these Terms are only for the purpose of organizing the
        various provisions under these Terms in an orderly manner and shall not
        be used by either Party to interpret the provisions contained herein in
        any manner. Further, it is specifically agreed to by the Parties that
        the headings shall have no legal or contractual value. <br />• The use
        of the Website and Application by the User is solely governed by these
        Terms read with the Privacy Policy and any modifications or amendments
        made thereto by the Company from time to time, at its sole discretion.
        Accessing the Application and/or using any of the information or
        Services provided therein shall be deemed to signify the User's
        unequivocal acceptance of these Terms and the aforementioned Policy, and
        the User expressly agrees to be bound by the same, regardless of however
        the User or anyone on the User's behalf has accessed, installed,
        downloaded or used the Application. The User expressly agrees and
        acknowledges that the Terms and Policy are co-terminus, and that expiry
        / termination of either one will lead to the termination of the other.
        The User may not access the Application or avail of any of the Services
        provided by the Company if the User does not accept and agree to be
        bound by the Terms and Policy. In the event that the User or anyone
        acting on the User's behalf does not wish to be bound by the Terms and
        the Policy, the User (or the legal person/entity acting on the User's
        behalf) unequivocally agrees to refrain from accessing, using or
        retaining the Application on any device in any manner whatsoever. The
        User agrees that anything done or caused to be done by the User or
        anyone acting on the User's behalf, whether expressly or impliedly in
        contravention with the Terms or Policy, will render the User liable for
        legal and punitive action. <br />
        <br />
        COLLECTION OF PERSONAL AND OTHER INFORMATION: - <br />
        <br />• The User is aware and acknowledges that the Company collects and
        stores the User’s personal information, which is provided by the User
        from time to time through the Application/website, including but not
        limited to the User’s user name, passwords, email address, name,
        address, age, date of birth, sex, nationality, geographical location,
        web browsing history, etc., as well as any images, chat messages or
        other information uploaded / published by the User through the
        Application/website. The User is aware that this information will be
        used by the Company/Application/website to provide services and features
        targeted at the User, that are most likely to meet the User’s needs, and
        also to customize and improve the Application to make its users’
        experiences safer and easier. <br />• The User is aware that the
        Company/Application may automatically track certain information about
        the User, based upon but not limited to, the User’s IP address and the
        User’s use of the Application, and the User expressly consents to the
        same. The User is expressly made aware that such information may include
        the browsing history of the User, whether or not a part of/through the
        Application. <br />• If the User chooses to avail of the Service through
        the Application, the User consents to allowing the Company/Application
        to collect information about the User’s behavior and trends. <br />• The
        User is aware that any and all information pertaining to the User
        collected by the Company, whether or not directly provided by the User
        to the Company/Application, including but not limited to personal
        correspondence such as emails, feedback from other users or third
        parties regarding the User’s activities or postings on the
        Application/website, etc., may be collected and complied by the Company
        into a file/folder specifically created for / allotted to the User, and
        the User hereby expressly consents to the same. <br />• The User is
        aware that while he/she may be able to browse/access some
        sections/features of the Application/website without being a registered
        user, certain activities, including but not limited to availing of the
        Service may require the User to provide valid personal information to
        the Company/Application/website for the purpose of registration. <br />
        <br />
        COOKIES: -<br />
        <br />
        • The User is aware that a ‘Cookie’ is a small piece of information
        stored by a web server on a web browser so it can later be traced back
        from that particular browser, and that cookies are useful for enabling
        the browser to remember information specific to a given user, including
        but not limited to a User’s login identification, password, etc. The
        User is aware that the Application places both permanent and temporary
        cookies in the User’s computer's hard drive and web browser and does
        hereby expressly consent to the same. <br />• The User is further aware
        that the Application uses data collection devices such as cookies to
        help analyze web page flow, measure promotional effectiveness, and
        promote trust and safety, and that certain features of the Application
        are only available through the use of such cookies. While the User is
        free to decline the Application’s cookies if the User’s device permits,
        the User may consequently be unable to use certain features on the
        Application. <br />• Additionally, the User is aware that he/she might
        encounter ‘cookies’ or other similar devices on the Application that are
        placed by third parties or affiliates of the Company. The User expressly
        agrees and acknowledges that the Company/Application does not control
        the use of such cookies/other devices by third parties, that the
        Company/Application is in no way responsible for the same, and that the
        User assumes any and all risks in this regard. <br />
        <br />
        DIVULGING/SHARING OF PERSONAL INFORMATION: - <br />
        <br />• The User is aware that the Application/Company/agency/website
        may share the User’s personal information with other entities and
        affiliates to help detect and prevent identity theft, fraud and other
        potentially illegal acts; correlate related or multiple accounts to
        prevent abuse of the Application’s services; and to facilitate joint or
        co-branded services, where such services are provided by more than one
        entity. <br />• The User is aware that the
        Application/Company/agency/website may disclose personal information if
        required to do so by law or if the Application/Company in good faith
        believes that such disclosure is reasonably necessary to respond to
        subpoenas, court orders, or other legal processes. The
        Application/Company/agency/website may also disclose the User’s personal
        information to law enforcement offices, third party rights owners, or
        other third parties if it believes that such disclosure is reasonably
        necessary to enforce the Terms or Policy; respond to claims that an
        advertisement, posting or other content violates the rights of a third
        party; or protect the rights, property or personal safety of its users,
        or the general public. <br />• The User is further aware that the
        Application/Company/agency website and its affiliates may share / sell
        some or all of the User’s personal information with other business
        entities should the Application/Company/agency/website(or its assets)
        plan to merge with, or be acquired by such business entity, or in the
        event of re-organization, amalgamation, or restructuring of the
        Company’s business. Such business entity or new entity will continue to
        be bound be the Terms and Policy, as may be amended from time to time.{' '}
        <br />• Notwithstanding anything contained herein or in the Terms of
        Service accompanying the present Policy, the User acknowledges that the
        Company/agency shall protect the confidentiality of all data provided by
        the User to the Application, and the User accordingly agrees that the
        Company shall not be held liable for any accidental dissemination of
        data that has occurred in spite of the Company’s best efforts and
        procedures to maintain confidentiality. <br />
        <br />
        USER’S CONSENT: - <br />
        <br />
        By using the Application/website and/ or by providing information to the
        Company through the Application/website, the User consents to the
        collection and use of the information disclosed by the User on the
        Application in accordance with this Policy, including but not limited to
        the User’s consent to the Company/Application/website/agency
        sharing/divulging the User’s information, as per the terms contained
        herein. <br />
        <br />
        Declaration: - <br />
        <br />I consciously declare that this platform is only for motivating us
        to find a donor or help a recipient who is in need of blood. If any
        occurrences happen as the donor has some dieses, any medical
        complications or money transactions/any other problem happens only the
        recipient and donor are responsible for it. This platform is not
        responsible for any of these occurrences. This company is just a media
        where the recipient and donor can find their required member to
        communicate. It does not support any social and economic transactions.
        If the recipient or donor faces any kind of problems between them only,
        they are to be blamed, the website is not responsible for any of these.
        Whenever I use this website/apps as a user (Donor/ recipient) I accept
        all the above terms and condition that is describe (top to bottom) in
        this page.
      </p>
    </div>
  );
};

TermsAndConditions.propTypes = {};

export default TermsAndConditions;
